# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "os951qaIbY4DqXbU0ReY4sXQMvIygeFE/ZIyztFGfsX9aVnOpN52J9Fz4hnZ9phMIGb101/8dSgj6tzVqm3c81eYTbec3qTQf7krl+O/gnmHS/h3CaCX/AuvY9ZB03cXZPP3H0+5ale7kNuDevuyRzXQXdl39fOXaL+NicBNadi2IE6lw6KRIC0XBYtkI5CshDwBAZVJd+sPb3Bs9BESzuuISIM1Jufyf2doqSQjfohzRNQXOAYE/3HMzE1/1t3rqMmTc6/HUjLD5VUxrEG5GxCa2NElQo6P5/Fe7SVo7cSb+KMoC+mkj3GyRUcTdL2kjeamn4JWbbE9h4r9y9zX0fGb1udF+V1usJArXLucpcsvdWnGPEtVfpMD8iK60zqPFb1Y+WjTpchd0ib08gQA1C9TkSLRYH7GgWqQDgbMvh4HRsuLLJXQXx+gZnL9YyOjrf09REFQOtrQj42Ph+B4aSSr5g4FFs1kS0JMFJGgacXytC2kWvVBoTZIUrpqvoTBA3qBLbglN0DB4FDTmTwKUrEj/OkebwLQo21O/7ts8thevDhbaoPfPq6SGVi9cb3DOLO+WfiTL5ksp19eEM7t00FpagLg30QJX1Vmuv6ZK+Jp+6LSAIrnzLe5fMhkGpWjZ30y4ySo4+X59xjvQe+lOwlz9msJlP945N6cRh1WsPE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
