travis:
  secure:
    BINSTAR_TOKEN: os951qaIbY4DqXbU0ReY4sXQMvIygeFE/ZIyztFGfsX9aVnOpN52J9Fz4hnZ9phMIGb101/8dSgj6tzVqm3c81eYTbec3qTQf7krl+O/gnmHS/h3CaCX/AuvY9ZB03cXZPP3H0+5ale7kNuDevuyRzXQXdl39fOXaL+NicBNadi2IE6lw6KRIC0XBYtkI5CshDwBAZVJd+sPb3Bs9BESzuuISIM1Jufyf2doqSQjfohzRNQXOAYE/3HMzE1/1t3rqMmTc6/HUjLD5VUxrEG5GxCa2NElQo6P5/Fe7SVo7cSb+KMoC+mkj3GyRUcTdL2kjeamn4JWbbE9h4r9y9zX0fGb1udF+V1usJArXLucpcsvdWnGPEtVfpMD8iK60zqPFb1Y+WjTpchd0ib08gQA1C9TkSLRYH7GgWqQDgbMvh4HRsuLLJXQXx+gZnL9YyOjrf09REFQOtrQj42Ph+B4aSSr5g4FFs1kS0JMFJGgacXytC2kWvVBoTZIUrpqvoTBA3qBLbglN0DB4FDTmTwKUrEj/OkebwLQo21O/7ts8thevDhbaoPfPq6SGVi9cb3DOLO+WfiTL5ksp19eEM7t00FpagLg30QJX1Vmuv6ZK+Jp+6LSAIrnzLe5fMhkGpWjZ30y4ySo4+X59xjvQe+lOwlz9msJlP945N6cRh1WsPE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
